#数据连接,
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springcloud_sell
    username: root
    password: root
  jpa:
    show-sql: true
  #redis配置
  redis:
    port: 6379
    host: 127.0.0.1
env: dev
